export const genders = ["Male","Female"];

export const indianStatesAndUTs = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
];

export const qualification = [ '10th','12th','Graduation','Post-graduation']

export const boards = [
    "CBSE",
    "CISCE(ICSE/ISC)",
    "Andhra Pradesh",
    "Assam",
    "Bihar",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "J & K",
    "Karnataka",
    "Kerala",
    "Maharashtra",
    "Madhya Pradesh",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Tamil Nadu",
    "Tripura",
    "Uttar Pradesh",
    "West Bengal",
    "Diploma",
    "Arunachal Pradesh",
    "Chhattisgarh",
    "Jharkhand",
    "Telangana",
    "IB(International Baccalaureate)",
    "Uttarakhand",
    "Other"
]

export const Course =[
    "B.Com",
    "B.A",
    "B.Arch",
    "B.Des.",
    "B.Ed",
    "B.Pharma",
    "B.Sc",
    "B.Tourism",
    "B.B.A/ B.M.S",
    "BCA",
    "BDS",
    "B.Tech/B.E.",
    "BFA",
    "BHM",
    "BVSC",
    "Diploma",
    "LLB",
    "MBBS",
    "BHMS",
    "BAMS",
    "B.El.Ed",
    "B.P.Ed",
    "BHMCT",
    "B.U.M.S",
    "ITI Certification",
    "Other"
]
export const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ];
export const yrs = [
    "2010", "2011", 
    "2012", "2013", "2014", "2015", "2016", "2017", 
    "2018", "2019", "2020", "2021", "2022", "2023", 
    "2024", "2025", "2026", "2027", "2028", "2029", 
    "2030", "2031", "2032"
];
  
export const specialization = [
    "Telecommunication",
    "Agriculture",
    "Automobile",
    "Aviation",
    "Bio-Chemistry/Bio-Technology",
    "Biomedical",
    "Ceramics",
    "Chemical",
    "Civil",
    "Computers",
    "Electrical",
    "Electrical and Electronics",
    "Electronics/Telecommunication",
    "Energy",
    "Environmental",
    "Information Technology",
    "Instrumentation",
    "Marine",
    "Mechanical",
    "Metallurgy",
    "Mineral",
    "Mining",
    "Nuclear",
    "Paint/Oil",
    "Petroleum",
    "Plastics",
    "Production/Industrial",
    "Textile",
    "Other",
]